// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import AutoExpandTextAreaController from "./auto_expand_text_area_controller"
application.register("auto-expand-text-area", AutoExpandTextAreaController)

import CounterInputController from "./counter_input_controller"
application.register("counter-input", CounterInputController)

import DarkModeController from "./dark_mode_controller"
application.register("dark-mode", DarkModeController)

import DateRangePickerController from "./date_range_picker_controller"
application.register("date-range-picker", DateRangePickerController)

import DropdownController from "./dropdown_controller"
application.register("dropdown", DropdownController)

import GalleryController from "./gallery_controller"
application.register("gallery", GalleryController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import HelpSearchController from "./help_search_controller"
application.register("help-search", HelpSearchController)

import InboxController from "./inbox_controller"
application.register("inbox", InboxController)

import InsightChartController from "./insight_chart_controller"
application.register("insight-chart", InsightChartController)

import InsightsController from "./insights_controller"
application.register("insights", InsightsController)

import ModalController from "./modal_controller"
application.register("modal", ModalController)

import NavController from "./nav_controller"
application.register("nav", NavController)

import PricingController from "./pricing_controller"
application.register("pricing", PricingController)

import PropertiesController from "./properties_controller"
application.register("properties", PropertiesController)

import ScrollSpyController from "./scroll_spy_controller"
application.register("scroll-spy", ScrollSpyController)

import SearchController from "./search_controller"
application.register("search", SearchController)

import SelectAllController from "./select_all_controller"
application.register("select-all", SelectAllController)

import SmoothScrollController from "./smooth_scroll_controller"
application.register("smooth-scroll", SmoothScrollController)

import TabsController from "./tabs_controller"
application.register("tabs", TabsController)

import VisibilityController from "./visibility_controller"
application.register("visibility", VisibilityController)
